export enum OrderStatus {
  CANCEL = 'CANCEL',
  WAITING_PAY = 'WAITING_PAY',
  PAID = 'PAID',
  DELIVERED = 'DELIVERED',
  RECEIPTED = 'RECEIPTED',
  CONFIRMED = 'CONFIRMED',
  REVIEWED = 'REVIEWED'
}
